services:
  # Postgres
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data

  # Postgres UI
  pgadmin:
    container_name: postgres-ui
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_ALLOW_SAVE_PASSWORD: "True"
    ports:
      - "5050:80"

  # MongoDB
  mongodb:
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongo_data:/data/db

  # MongoDB UI
  mongodb_ui:
    container_name: mongodb-ui
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"

  # Airflow
  airflow-db:
    container_name: airflow-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

  airflow:
    container_name: airflow
    volumes:
      - ./pipelines/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
    env_file:
      - .env
    environment:
      PYTHONPATH: /opt/airflow/src
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__PARALLELISM: 16
      AIRFLOW__CORE__DAG_CONCURRENCY: 8
      AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: 2
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
    ports:
      - "8080:8080"
    command: >
      bash -c '(airflow db init && 
      airflow users create 
      --username admin 
      --password admin 
      --firstname admin 
      --lastname admin 
      --role Admin
      --email admin@gmail.com);
      airflow webserver & airflow scheduler'

  # Backend
  backend:
    container_name: paper-submission-rcm-system-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
