services:
  # Jupyter Notebook
  notebook:
    container_name: jupyter-notebook
    ports:
      - "8888:8888"

  # Postgres
  postgres:
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Postgres UI
  pgadmin:
    container_name: postgres-UI
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # MongoDB
  mongodb:
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # MongoDB UI
  mongodb_ui:
    container_name: mongodb-UI
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  # Airflow
  airflow:
    container_name: airflow
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  mongo_data:
