services:
  # Jupyter Notebook
  notebook:
    build: ./notebooks
    volumes:
      - .:/workspace

  # Postgres
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb

  # Postgres UI
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_ALLOW_SAVE_PASSWORD: "True"

  # MongoDB
  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  # MongoDB UI
  mongodb_ui:
    image: mongo-express:1.0.0
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb

  # Airflow
  airflow:
    build: ./pipelines
    volumes:
      - ./pipelines/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
    environment:
      PYTHONPATH: /opt/airflow/src
    command: >
      bash -c '(airflow db init && 
      airflow users create 
      --username admin 
      --password admin 
      --firstname admin 
      --lastname admin 
      --role Admin
      --email admin@gmail.com);
      airflow webserver & airflow scheduler'
