services:
  # Jupyter Notebook
  notebook:
    build: ./notebooks
    expose:
      - "8888"

  # Postgres
  postgres:
    image: postgres:15
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Postgres UI
  pgadmin:
    image: dpage/pgadmin4
    expose:
      - "80"
    depends_on:
      - postgres

  # MongoDB
  mongodb:
    image: mongo:6.0
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db

  # MongoDB UI
  mongodb_ui:
    image: mongo-express:1.0.0
    expose:
      - "8081"
    depends_on:
      - mongodb

  # Milvus
  etcd:
    image: quay.io/coreos/etcd:v3.5.18
    volumes:
      - etcd:/etcd

  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    expose:
      - "9001"
      - "9000"
    volumes:
      - minio_data:/minio_data

  milvus:
    image: milvusdb/milvus:v2.6.3
    expose:
      - "19530"
      - "9091"
    volumes:
      - milvus:/var/lib/milvus
    depends_on:
      - "etcd"
      - "minio"

  # Airflow
  airflow:
    build: ./pipelines
    expose:
      - "8080"

volumes:
  mongo_data:
  postgres_data:
  etcd:
  minio_data:
